set timeout 3
#
# expectations that clean up in case of error. Note that `$test' is
# a purely local variable.
#
# The first of these is used to match any bad responses, and resynchronise
# things by finding a prompt. The second is a timeout error, and shouldn't
# ever be triggered.
#
expect_after {
	-re "\[^\n\r\]*$prompt$" {
		fail "$test (bad match)"
		if { $verbose > 0 } {
			regexp ".*\r\n(\[^\r\n\]+)(\[\r\n\])+$prompt$" \
						$expect_out(buffer) "" output
			send_user "\tUnmatched output: \"$output\"\n"
		}
	}
	timeout {
		fail "$test (timeout)"
	}
}



#
# The following tests use the local flat-Earth approximation to distance (in
# which meridians converge).
#



#
# Test with point B 1 km east of point A on the equator and at latitudes 45 and
# 80 degrees.
#
local_distance_test  0 0  0 [expr 1/($dd*cos($deg2rad* 0))] 1 "B 1 km E of A at equator"
local_distance_test 45 0 45 [expr 1/($dd*cos($deg2rad*45))] 1 "B 1 km E of A at lat=45"
local_distance_test 80 0 80 [expr 1/($dd*cos($deg2rad*80))] 1 "B 1 km E of A at lat=80"



#
# Test with point B 2 km west of point A on the equator and at latitudes 45 and
# 80 degrees.
#
local_distance_test  0 0  0 [expr -2/($dd*cos($deg2rad* 0))] 2 "B 2 km W of A at equator"
local_distance_test 45 0 45 [expr -2/($dd*cos($deg2rad*45))] 2 "B 2 km W of A at lat=45"
local_distance_test 80 0 80 [expr -2/($dd*cos($deg2rad*80))] 2 "B 2 km W of A at lat=80"



#
# Test with point B 5 km north of point A with the reference point on the
# equator and at latitudes 45 and 80 degrees.
#
local_distance_test  0 0 [expr    5/$dd] 0 5 "B 5 km N of A at equator"
local_distance_test 45 0 [expr 45+5/$dd] 0 5 "B 5 km N of A at lat=45"
local_distance_test 80 0 [expr 80+5/$dd] 0 5 "B 5 km N of A at lat=80"



#
# Test with point B 10 km south of point A with the reference point on the
# equator and at latitudes 45 and 80 degrees.
#
local_distance_test  0 0 [expr   -10/$dd] 0 10 "B 10 km S of A at equator"
local_distance_test 45 0 [expr 45-10/$dd] 0 10 "B 10 km S of A at lat=45"
local_distance_test 80 0 [expr 80-10/$dd] 0 10 "B 10 km S of A at lat=80"



#
# Test with point B 1 km northeast of point A with the reference point on the
# equator and at latitudes 45 and 80 degrees.
#
local_distance_test  0 0 [expr    sqrt(0.5)/$dd] [expr sqrt(0.5)/($dd*cos($deg2rad* 0))] 1 "B 1 km NE of A at equator"
local_distance_test 45 0 [expr 45+sqrt(0.5)/$dd] [expr sqrt(0.5)/($dd*cos($deg2rad*45))] 1 "B 1 km NE of A at lat=45"
local_distance_test 80 0 [expr 80+sqrt(0.5)/$dd] [expr sqrt(0.5)/($dd*cos($deg2rad*80))] 1 "B 1 km NE of A at lat=80"



#
# Test with point B 1 km east of point A, on opposite sides of the +180/-180
# line, with the reference point on the equator and at latitudes 45 and 80
# degrees.
#
local_distance_test  0 [expr 180-0.5/($dd*cos($deg2rad* 0))]  0 [expr -180+0.5/($dd*cos($deg2rad* 0))] 1 "B 1 km E of A, across +180/-180 line, at equator"
local_distance_test 45 [expr 180-0.5/($dd*cos($deg2rad*45))] 45 [expr -180+0.5/($dd*cos($deg2rad*45))] 1 "B 1 km E of A, across +180/-180 line, at lat=45"
local_distance_test 80 [expr 180-0.5/($dd*cos($deg2rad*80))] 80 [expr -180+0.5/($dd*cos($deg2rad*80))] 1 "B 1 km E of A, across +180/-180 line, at lat=80"



#
# Test with point B 1 km northeast of point A, on opposite sides of the
# +180/-180 line, with the reference point on the equator and at latitudes 45
# and 80 degrees.
#
local_distance_test  0 [expr 180-sqrt(0.5)/($dd*cos($deg2rad* 0))/2] [expr    sqrt(0.5)/$dd] [expr -180+sqrt(0.5)/($dd*cos($deg2rad* 0))/2] 1 "B 1 km NE of A, across +180/-180 line, at equator"
local_distance_test 45 [expr 180-sqrt(0.5)/($dd*cos($deg2rad*45))/2] [expr 45+sqrt(0.5)/$dd] [expr -180+sqrt(0.5)/($dd*cos($deg2rad*45))/2] 1 "B 1 km NE of A, across +180/-180 line, at lat=45"
local_distance_test 80 [expr 180-sqrt(0.5)/($dd*cos($deg2rad*80))/2] [expr 80+sqrt(0.5)/$dd] [expr -180+sqrt(0.5)/($dd*cos($deg2rad*80))/2] 1 "B 1 km NE of A, across +180/-180 line, at lat=80"
