set timeout 3
#
# expectations that clean up in case of error. Note that `$test' is
# a purely local variable.
#
# The first of these is used to match any bad responses, and resynchronise
# things by finding a prompt. The second is a timeout error, and shouldn't
# ever be triggered.
#
expect_after {
	-re "\[^\n\r\]*$prompt$" {
		fail "$test (bad match)"
		if { $verbose > 0 } {
			regexp ".*\r\n(\[^\r\n\]+)(\[\r\n\])+$prompt$" \
						$expect_out(buffer) "" output
			send_user "\tUnmatched output: \"$output\"\n"
		}
	}
	timeout {
		fail "$test (timeout)"
	}
}

set sdd [expr $dd * $dd]



#
# The following tests are of the polygon area calculation that uses a local
# flat-Earth approximation (in which meridians converge).
#

#
# Test with an empty polygon.
#
local_polygon_area_test { } 0 "empty polygon"



#
# Test with single-point polygons, on the equator and at latitudes 45 and 80
# degrees.
#
local_polygon_area_test {  0 0 } 0 "single-point polygon 1 at equator"
local_polygon_area_test { 45 0 } 0 "single-point polygon 1 at lat=45"
local_polygon_area_test { 80 0 } 0 "single-point polygon 1 at lat=80"
local_polygon_area_test {  1 1 } 0 "single-point polygon 2 at equator"
local_polygon_area_test { 46 1 } 0 "single-point polygon 2 at lat=45"
local_polygon_area_test { 81 1 } 0 "single-point polygon 2 at lat=80"



#
# Test with two-point (line) polygons.
#
local_polygon_area_test {  0 0   1 0 } 0 "two-point (line) polygon 1 at equator"
local_polygon_area_test { 45 0  46 0 } 0 "two-point (line) polygon 1 at lat=45"
local_polygon_area_test { 80 0  81 0 } 0 "two-point (line) polygon 1 at lat=80"
local_polygon_area_test {  2 2   1 1 } 0 "two-point (line) polygon 2 at equator"
local_polygon_area_test { 47 2  46 1 } 0 "two-point (line) polygon 2 at lat=45"
local_polygon_area_test { 83 2  82 1 } 0 "two-point (line) polygon 2 at lat=80"



#
# Test with some triangles.
# The multiplier for the area is (cos(minlat) + cos(maxlat))/2.
#

#
#   ^
#   |
# 2 +
#   |
#   |
#   |
# 1 *****
#   *  *
#   * *
#   **
#   *---+---+->
#  0    1   2
#
set mult [expr (1.0+cos($deg2rad*1))*0.5]
local_polygon_area_test {  0 0   1 0   1 1 } [expr 0.5 * $sdd * $mult] "triangle 1 at equator"
set mult [expr (cos($deg2rad*45)+cos($deg2rad*46))*0.5]
local_polygon_area_test { 45 0  46 0  46 1 } [expr 0.5 * $sdd * $mult] "triangle 1 at lat=45"
set mult [expr (cos($deg2rad*80)+cos($deg2rad*81))*0.5]
local_polygon_area_test { 80 0  81 0  81 1 } [expr 0.5 * $sdd * $mult] "triangle 1 at lat=80"

#
#   0    1   2   3
#    *********---+->
#    |*     *
#    | *   *
#    |  * *
# -1 +   *
#    |
#    v
#
set mult [expr (cos($deg2rad*-1)+1.0)*0.5]
local_polygon_area_test {  0 0   0 2  -1 1 } [expr 1.0 * $sdd * $mult] "triangle 2 at equator"
set mult [expr (cos($deg2rad*44)+cos($deg2rad*45))*0.5]
local_polygon_area_test { 45 0  45 2  44 1 } [expr 1.0 * $sdd * $mult] "triangle 2 at lat=45"
set mult [expr (cos($deg2rad*79)+cos($deg2rad*80))*0.5]
local_polygon_area_test { 80 0  80 2  79 1 } [expr 1.0 * $sdd * $mult] "triangle 2 at lat=80"

#
#   ^
#   |
# 3 +       *
#   |      **
#   |     * *
#   |    * *
# 2 +   *  *
#   |  *  *
#   | *   *
#   |*    *
# 1 *    *
#   |*   *
#   | * *
#   |  **
#   +---*---+->
#  0    1   2
#
set mult [expr (1.0+cos($deg2rad*3))*0.5]
local_polygon_area_test {  1 0   3 2   0 1 } [expr 2.0 * $sdd * $mult] "triangle 3 at equator"
set mult [expr (cos($deg2rad*45)+cos($deg2rad*48))*0.5]
local_polygon_area_test { 46 0  48 2  45 1 } [expr 2.0 * $sdd * $mult] "triangle 3 at lat=45"
set mult [expr (cos($deg2rad*80)+cos($deg2rad*83))*0.5]
local_polygon_area_test { 81 0  83 2  80 1 } [expr 2.0 * $sdd * $mult] "triangle 3 at lat=80"



#
# Test with some squares, rectangles, and other quadrilaterals.
#

#
#   ^
#   |
# 1 *****
#   *   *
#   *   *
#   *   *
#   *****---+->
#  0    1   2
#
set mult [expr (1.0+cos($deg2rad*1))*0.5]
local_polygon_area_test {  0 0   1 0   1 1   0 1 } [expr 1.0 * $sdd * $mult] "square 1 at equator"
set mult [expr (cos($deg2rad*45)+cos($deg2rad*46))*0.5]
local_polygon_area_test { 45 0  46 0  46 1  45 1 } [expr 1.0 * $sdd * $mult] "square 1 at lat=45"
set mult [expr (cos($deg2rad*80)+cos($deg2rad*81))*0.5]
local_polygon_area_test { 80 0  81 0  81 1  80 1 } [expr 1.0 * $sdd * $mult] "square 1 at lat=80"

#
#           ^
#           |
#         1 +
#           |
#         *****
#         * | *
# <-+---+-*-+-*-+---+->
#  -2  -1 * | * 1   2
#         *****
#           |
#        -1 +
#           |
#           v
#
set mult [expr (cos($deg2rad*-0.5)+cos($deg2rad*0.5))*0.5]
local_polygon_area_test {  0.5 -0.5   0.5 0.5  -0.5 0.5  -0.5 -0.5 } [expr 1.0 * $sdd * $mult] "square 2 at equator"
set mult [expr (cos($deg2rad*44.5)+cos($deg2rad*45.5))*0.5]
local_polygon_area_test { 45.5 -0.5  45.5 0.5  44.5 0.5  44.5 -0.5 } [expr 1.0 * $sdd * $mult] "square 2 at lat=45"
set mult [expr (cos($deg2rad*79.5)+cos($deg2rad*80.5))*0.5]
local_polygon_area_test { 80.5 -0.5  80.5 0.5  79.5 0.5  79.5 -0.5 } [expr 1.0 * $sdd * $mult] "square 2 at lat=80"

#
#           ^
#           |
#       *************
#       *   |       *
#       *   |       *
#       *   |       *
# <-+---*************---+->
#  -2  -1   0   1   2   3
#
set mult [expr (1.0+cos($deg2rad*1))*0.5]
local_polygon_area_test {  0 -1   1 -1   1 2   0 2 } [expr 3.0 * $sdd * $mult] "rectangle 1 at equator"
set mult [expr (cos($deg2rad*45)+cos($deg2rad*46))*0.5]
local_polygon_area_test { 45 -1  46 -1  46 2  45 2 } [expr 3.0 * $sdd * $mult] "rectangle 1 at lat=45"
set mult [expr (cos($deg2rad*80)+cos($deg2rad*81))*0.5]
local_polygon_area_test { 80 -1  81 -1  81 2  80 2 } [expr 3.0 * $sdd * $mult] "rectangle 1 at lat=80"

#
#   ^
#   |
# 3 +             ***
#   |         ****  *
#   |      ***      *
#   |  ****         *
# 2 ***             *
#   *               *
#   *               *
#   *               *
# 1 *             ***
#   *         ****
#   *      ***
#   *  ****
#   ***-+---+---+---+---+->
#  0    1   2   3   4   5
#
set mult [expr (1.0+cos($deg2rad*3))*0.5]
local_polygon_area_test {  0 0   2 0   3 4   1 4 } [expr 8.0 * $sdd * $mult] "parallelogram 1 at equator"
set mult [expr (cos($deg2rad*45)+cos($deg2rad*48))*0.5]
local_polygon_area_test { 45 0  47 0  48 4  46 4 } [expr 8.0 * $sdd * $mult] "parallelogram 1 at lat=45"
set mult [expr (cos($deg2rad*80)+cos($deg2rad*83))*0.5]
local_polygon_area_test { 80 0  82 0  83 4  81 4 } [expr 8.0 * $sdd * $mult] "parallelogram 1 at lat=80"



#
# Test with larger shapes.
#

#
#   ^
#   |
# 2 +   *****
#   |  *     *
#   | *       *
#   |*         *
# 1 *           *
#   |*         *
#   | *       *
#   |  *     *
#   +---*****---+->
#  0    1   2   3
#
set mult [expr (1.0+cos($deg2rad*2))*0.5]
local_polygon_area_test {  1 0   2 1   2 2   1 3   0 2   0 1 } [expr 4.0 * $sdd * $mult] "hexagon 1 at equator"
set mult [expr (cos($deg2rad*45)+cos($deg2rad*47))*0.5]
local_polygon_area_test { 46 0  47 1  47 2  46 3  45 2  45 1 } [expr 4.0 * $sdd * $mult] "hexagon 1 at lat=45"
set mult [expr (cos($deg2rad*80)+cos($deg2rad*82))*0.5]
local_polygon_area_test { 81 0  82 1  82 2  81 3  80 2  80 1 } [expr 4.0 * $sdd * $mult] "hexagon 1 at lat=80"



#
# Test with concave shapes.
#

#
#   ^
#   |
# 2 +   *
#   |  * *
#   | *   *
#   |*     *
# 1 *   *   *
#   *  * *  *
#   * *   * *
#   **     **
#   *---+---*---+->
#  0    1   2   3
#
set mult [expr (1.0+cos($deg2rad*2))*0.5]
local_polygon_area_test {  0 0   1 0   2 1   1 2   0 2   1 1 } [expr 2.0 * $sdd * $mult] "concave 1 at equator"
set mult [expr (cos($deg2rad*45)+cos($deg2rad*47))*0.5]
local_polygon_area_test { 45 0  46 0  47 1  46 2  45 2  46 1 } [expr 2.0 * $sdd * $mult] "concave 1 at lat=45"
set mult [expr (cos($deg2rad*80)+cos($deg2rad*82))*0.5]
local_polygon_area_test { 80 0  81 0  82 1  81 2  80 2  81 1 } [expr 2.0 * $sdd * $mult] "concave 1 at lat=80"

#
#   ^
#   |
# 4 +
#   |
#   |
#   |
# 3 *****   *****
#   *   *   *   *
#   *   *   *   *
#   *   *   *   *
# 2 *   *****   *
#   *           *
#   *           *
#   *           *
# 1 *   *****   *
#   *   *   *   *
#   *   *   *   *
#   *   *   *   *
#   *****---*****---+->
#  0    1   2   3   4
#
set mult [expr (1.0+cos($deg2rad*3))*0.5]
local_polygon_area_test {  0 0   3 0   3 1   2 1   2 2   3 2   3 3   0 3   0 2   1 2   1 1   0 1 } [expr 7.0 * $sdd * $mult] "wanna buy an H at equator"
set mult [expr (cos($deg2rad*45)+cos($deg2rad*48))*0.5]
local_polygon_area_test { 45 0  48 0  48 1  47 1  47 2  48 2  48 3  45 3  45 2  46 2  46 1  45 1 } [expr 7.0 * $sdd * $mult] "wanna buy an H at lat=45"
set mult [expr (cos($deg2rad*80)+cos($deg2rad*83))*0.5]
local_polygon_area_test { 80 0  83 0  83 1  82 1  82 2  83 2  83 3  80 3  80 2  81 2  81 1  80 1 } [expr 7.0 * $sdd * $mult] "wanna buy an H at lat=80"
